// Hand-written seed profiles and their posts. Pure data: no I/O, no Prisma.
// Order matters: the index of a user and of each of their posts feeds the
// deterministic follow/like/timestamp arithmetic in seed-data.ts, and posts
// are referenced as `{ username, index }` by the seeded comments. `demo`
// must stay first — it is the documented sample account.

export interface SeedUserProfile {
  username: string;
  displayName: string;
  bio: string;
  // Newest first: index 0 is the most recent post.
  posts: readonly string[];
}

export const DEMO_USERNAME = 'demo';

export const SEED_USERS: readonly SeedUserProfile[] = [
  {
    username: DEMO_USERNAME,
    displayName: 'Demo User',
    bio: 'Just here to try things out. Coffee, side projects and too many open tabs.',
    posts: [
      'Finally cleaned up my desk. Productivity went up by at least 3%.',
      'Hot take: the best feature of any app is a fast search box.',
      'Trying a new rule this week: no phone for the first hour after waking up. Day two and still alive.',
      'Anyone else keep a list of books they will "definitely read next"? Mine is 74 items long.',
      'Made pancakes from scratch this morning and nobody asked, but they were great.',
      'Hello everyone! First post here. Tell me what you are working on this week.',
    ],
  },
  {
    username: 'ana_torres',
    displayName: 'Ana Torres',
    bio: 'Product designer. I care about empty states more than I should. Based in Madrid.',
    posts: [
      'Reminder that an empty state is the first impression for every new user. Design it on purpose.',
      'Spent the afternoon removing three settings nobody used. Best design work of the week.',
      'Hot chocolate and wireframes. Perfect rainy day.',
      'If your onboarding needs a tutorial, the onboarding is the problem.',
      'Hallway usability test with my neighbour: she found the bug in 40 seconds. Humbling.',
      'New sketchbook, who dis.',
      'Designers: what is the one Figma plugin you could not work without?',
    ],
  },
  {
    username: 'dan_okafor',
    displayName: 'Daniel Okafor',
    bio: 'Backend engineer. Databases, queues and the occasional bad pun. Opinions are my own.',
    posts: [
      'Added an index, query went from 2.3s to 4ms. I will be insufferable for the rest of the day.',
      'Every "temporary" cron job I have written is still running somewhere.',
      'Keyset pagination is one of those things you learn once and then use everywhere.',
      'Friday deploys are fine if you like surprises on Saturday.',
      'Wrote a migration, then a rollback, then a rollback for the rollback. Classic Tuesday.',
      'SQLite is criminally underrated for small apps.',
    ],
  },
  {
    username: 'priya_codes',
    displayName: 'Priya Raman',
    bio: 'ML engineer. Turning messy data into slightly less messy data. Chai enthusiast.',
    posts: [
      'Spent two days tuning a model. The fix was a mislabeled column in the training set.',
      'The most important ML skill is looking at your data. Actually looking at it.',
      'Chai count today: four. Bugs fixed: also four. Correlation or causation?',
      'Gave a talk on evaluation metrics today. Accuracy is not a strategy.',
      'My notebook has cells numbered 1, 2, 47, 3. Please do not ask.',
      'Weekend plan: absolutely no GPUs. Just a long walk and a good book.',
      'Reading group this week covered data drift. Everyone left slightly scared.',
      'Pro tip: write down the baseline before you start improving it.',
    ],
  },
  {
    username: 'marcus_bakes',
    displayName: 'Marcus Bell',
    bio: 'Home baker. Sourdough, croissants and a starter named Doughvid. Sharing crumb shots daily.',
    posts: [
      "Today's sourdough: open crumb, crackly crust, zero regrets.",
      'Laminated dough is 20% technique and 80% keeping your kitchen cold.',
      'Doughvid (my starter) turned three this week. He gets a special rye feed.',
      'First attempt at cinnamon rolls with cardamom. The house smells unreal.',
      'Baking tip: weigh your ingredients. Cups are a lie.',
      'Burned a whole tray of cookies because I got distracted by a documentary about bread.',
    ],
  },
  {
    username: 'sofia_runs',
    displayName: 'Sofía Herrera',
    bio: 'Marathon runner, physio, morning person. 12 marathons and counting.',
    posts: [
      '18 km easy run today. The sunrise was worth the alarm.',
      'Your easy runs should feel easy. Really. Slow down.',
      "New shoes, same knees. Let's see how this goes.",
      'Signed up for a trail race in the mountains. What have I done.',
      'Recovery is part of training. Taking a full rest day and not feeling guilty about it.',
      'Physio reminder: strengthen your calves. Future you says thanks.',
      'Ran past a bakery at kilometre 14. Longest kilometre of my life.',
    ],
  },
  {
    username: 'kenji_photo',
    displayName: 'Kenji Watanabe',
    bio: 'Street photographer. 35mm, mostly black and white. Tokyo and wherever the train goes.',
    posts: [
      'Rain on the crosswalk, umbrellas everywhere. Best light of the month.',
      'Shot a full roll without looking at a screen once. Highly recommend.',
      'The best camera is the one you carry. Mine is getting heavy though.',
      'Found an old lens at a flea market for the price of a coffee. It is perfect.',
      'Street photography is mostly waiting. And then two seconds of luck.',
    ],
  },
  {
    username: 'lena_reads',
    displayName: 'Lena Fischer',
    bio: 'Librarian and reader. I will recommend you a book whether you asked or not.',
    posts: [
      'Finished a 900-page novel and immediately felt lonely. Recommendations for what to read next?',
      'Libraries are the last place you can sit for hours without being expected to buy anything.',
      'Reread a book from my teens. It was worse, and also better.',
      'Current stack on my nightstand: two mysteries, one history book, one I pretend to read.',
      'Someone returned a book today with a pressed flower inside. Kept it on the desk all day.',
      'Audiobooks count as reading. I will not be taking questions.',
    ],
  },
  {
    username: 'omar_travels',
    displayName: 'Omar Haddad',
    bio: 'Travel writer. Slow trains, street food and getting lost on purpose.',
    posts: [
      'Took the overnight train instead of flying. Saw three countries through the window.',
      'Best meal of the trip came from a stall with no name and one plastic stool.',
      'Packing light is a skill. I am still working on it.',
      'Got lost in the old town for two hours and found the best bookshop I have ever seen.',
      'Learn how to say "thank you" in the local language. It opens every door.',
      'Delayed six hours at the airport. Wrote half an article. Silver linings.',
      'Travel tip: walk the city on your first day with no plan. Your map will make sense after.',
    ],
  },
  {
    username: 'chloe_plants',
    displayName: 'Chloe Martin',
    bio: 'Houseplant collector with a small apartment and big ambitions. 63 plants, 1 cat.',
    posts: [
      'My monstera put out a new leaf and I told everyone I know.',
      'Overwatering kills more plants than neglect. Put the watering can down.',
      'The cat has decided the fern is her bed now. The fern disagrees.',
      'Propagation station is getting out of hand. Anyone want a pothos cutting?',
      'Bought a grow light. The living room now looks like a spaceship. Worth it.',
      "Plant 64 is arriving tomorrow. Don't tell my landlord.",
    ],
  },
  {
    username: 'ivan_chess',
    displayName: 'Ivan Petrov',
    bio: 'Chess coach. Endgames are beautiful. Blitz is chaos. I love both.',
    posts: [
      'Lost a winning endgame in blitz because I premoved. Never premove.',
      'Students always want openings. Teach them endgames first and they win more games.',
      'Played a 12-year-old at the club today. He crushed me and then asked for a snack.',
      "Rook endgames are always drawn. Except when they aren't.",
      'Solving puzzles with coffee is the best way to start the day.',
      'Tournament this weekend. Seven rounds, too little sleep, a lot of fun.',
      'Chess tip: before every move, ask what your opponent wants.',
      'Finally reached my rating goal for the year. Next goal: stop blundering on move 30.',
    ],
  },
  {
    username: 'grace_music',
    displayName: 'Grace Kim',
    bio: 'Cellist in a string quartet. Bach in the morning, film scores at night.',
    posts: [
      'Four hours of rehearsal and my hands are tired but my heart is full.',
      'Every cellist has a love-hate relationship with the Bach suites. Mostly love.',
      'Played at a small wedding today. The couple cried, the quartet cried, it was lovely.',
      'Carrying a cello through the city is basically a full-body workout.',
      'New strings day. The first hour always sounds like a different instrument.',
      'Listening to film scores on repeat while practicing scales. It helps. Somehow.',
    ],
  },
  {
    username: 'juan_cycles',
    displayName: 'Juan Morales',
    bio: 'Urban planner and daily cyclist. Better streets make better cities.',
    posts: [
      'Rode to work in 18 minutes. Driving takes 35. Bikes win again.',
      'A painted line is not bike infrastructure. Protected lanes or bust.',
      'Weekend ride along the river. Saw more cyclists than cars. The future is close.',
      'Trees on a street cool it down by several degrees. Plant more trees.',
      'City council meeting tonight about the new bike lane. Wish me luck.',
      'The bike lane got approved! Small wins matter.',
      'Fixed my own flat tyre in under ten minutes. Personal record.',
    ],
  },
  {
    username: 'hannah_vet',
    displayName: 'Hannah Brooks',
    bio: 'Small animal vet. I have seen things. Mostly socks swallowed by labradors.',
    posts: [
      "Removed a sock from a labrador today. Third one this month. It's always a lab.",
      "Please brush your pet's teeth. Your vet is begging you.",
      'A tiny kitten fell asleep on my arm during a checkup. Best part of the week.',
      'Long shift, but every patient went home happy. Time for a very long shower.',
      'Dog owners: chocolate, grapes and onions. Keep them away.',
      'Adopt older pets. They are calm, grateful, and already know how to sit.',
    ],
  },
  {
    username: 'raj_startups',
    displayName: 'Raj Mehta',
    bio: 'Two-time founder. Currently building tools for small bakeries. Talk to your users.',
    posts: [
      'Talked to 12 customers this week. Threw away half our roadmap. Best decision.',
      'Your first version should embarrass you a little. Ship it anyway.',
      'Founders: sleep is not optional. I learned that the hard way.',
      'Closed our first annual contract today. Celebrating with the team and a lot of pizza.',
      'Pricing is a product decision, not a finance decision.',
      'Hiring advice: look for people who ask good questions in the interview.',
      "Visited a customer's bakery to watch them use our app at 5am. Learned so much.",
    ],
  },
  {
    username: 'maya_climbs',
    displayName: 'Maya Cohen',
    bio: 'Boulderer, route setter, chalk everywhere. Falling is part of climbing.',
    posts: [
      'Sent my project after 23 sessions. I screamed a little. Maybe a lot.',
      'Set a new circuit at the gym today. Watching people figure out the beta is the best part.',
      'Climbing tip: use your legs. Your arms will thank you.',
      'Outdoor bouldering this weekend. Fingers are shredded, soul is restored.',
      'Rest days make you stronger. I keep telling myself that.',
    ],
  },
  {
    username: 'tom_gardens',
    displayName: 'Tom Whitaker',
    bio: 'Allotment gardener. Tomatoes, courgettes and an ongoing war with slugs.',
    posts: [
      'Picked the first tomatoes of the season. Ate three before I got home.',
      'The slugs have won this round. But the war is not over.',
      'Too many courgettes again. Every year I plant six and every year I regret it.',
      'Compost is just patience you can put in a bin.',
      'Swapped seeds with the neighbouring plot. Trying a purple bean this year.',
      'Rain all week. The garden is happy, I am muddy.',
      'Gardening tip: plant marigolds between your vegetables. The bees will come.',
    ],
  },
  {
    username: 'nadia_art',
    displayName: 'Nadia Rahman',
    bio: "Illustrator. Children's books, cats in hats, and far too many sketchbooks.",
    posts: [
      "Finished the cover for a children's book about a cat who runs a bakery. My dream job.",
      'Drawing hands is hard. Drawing cat paws is harder. Drawing cat paws holding bread is chaos.',
      'Sketchbook tip: draw every day, even if it is just a cup on your desk.',
      'Watercolour is 50% skill and 50% accepting what the water decides.',
      'Commissions open again next month. Mostly pets, sometimes pets in hats.',
      "Took my sketchbook to the park and drew strangers' dogs. Everyone wanted a copy.",
    ],
  },
  {
    username: 'leo_films',
    displayName: 'Leo Russo',
    bio: 'Film nerd. Watching one movie a day this year. Currently on day 243.',
    posts: [
      'Rewatched a classic noir tonight. They really did lighting better back then.',
      'Hot take: most movies would be better at 100 minutes.',
      'Went to a midnight screening alone. Best cinema experience of the year.',
      'The soundtrack carried that film and I will not hear otherwise.',
      'Day 243 of a movie a day. My watchlist is somehow longer than when I started.',
      'Reminder that subtitles are good, actually.',
      'Watched a silent film with a live orchestra. Goosebumps the entire time.',
    ],
  },
  {
    username: 'zoe_astro',
    displayName: 'Zoe Adams',
    bio: 'Amateur astronomer. Dark skies, cold nights, warm tea.',
    posts: [
      "Clear sky tonight! Saw Saturn's rings through the telescope and gasped out loud.",
      'Light pollution is a real problem. Please point your garden lights down.',
      'Meteor shower peaks this week. Bring a blanket and be patient.',
      'Drove two hours to find dark skies. The Milky Way was worth every minute.',
      'Photographed the moon with my phone through the eyepiece. Surprisingly decent.',
      'Cloudy for the ninth night in a row. Astronomy is mostly weather watching.',
    ],
  },
  {
    username: 'samuel_cooks',
    displayName: 'Samuel Mensah',
    bio: 'Chef. West African flavours, weeknight recipes, and jollof debates.',
    posts: [
      'Made jollof for 40 people today. Not a single grain left. Victory.',
      'Salt your pasta water. Like, properly salt it.',
      'A sharp knife is safer than a dull one. Go sharpen your knives.',
      'Tested a new peanut stew recipe on the staff. They asked for seconds and the recipe.',
      'Cooking tip: taste as you go. Every time.',
      'Market day. Bought far too many peppers and zero regrets.',
      'The secret ingredient is almost always more garlic.',
    ],
  },
  {
    username: 'elena_data',
    displayName: 'Elena Popescu',
    bio: 'Data analyst. SQL by day, charts by night. Bar charts start at zero.',
    posts: [
      'Your bar chart y-axis must start at zero. I will die on this hill.',
      'Wrote a 200-line SQL query and it worked on the first try. Suspicious.',
      'The dashboard nobody opens is still the one everyone asks about in meetings.',
      'Pie charts are fine for two slices. Anything more and I start to worry.',
      'Cleaned a dataset where "N/A", "n/a", "none" and "-" all meant the same thing.',
      'A good chart answers one question. A great one makes you ask the next.',
    ],
  },
  {
    username: 'ben_retro',
    displayName: 'Ben Carter',
    bio: "Retro gaming collector. Cartridges, CRTs and blowing into things that don't need it.",
    posts: [
      'Found a boxed copy of a game I rented as a kid. Paid way too much. No regrets.',
      'CRT TVs make old games look how they were meant to look. Fight me.',
      'Beat a platformer from 1991 without save states. My thumbs are sore.',
      'Cleaned the contacts on an old cartridge and it booted first try. Magic.',
      'Local game shop is closing. Went to say goodbye and left with three games.',
      'Speedrunners are the most dedicated people on the internet.',
    ],
  },
  {
    username: 'aisha_teaches',
    displayName: 'Aisha Bello',
    bio: 'Secondary school science teacher. Explosions (safe ones), questions and coffee.',
    posts: [
      'A student asked why the sky is blue and we spent the whole lesson on light. Best class all term.',
      'Marking 90 lab reports this weekend. Send coffee.',
      'Did the elephant toothpaste experiment. Thirty teenagers screamed with joy.',
      'Teachers: what is your favourite way to start a lesson?',
      'One kid said science is "just asking why until someone gets annoyed". Correct.',
      'End of term. Tired, proud, and already planning next year.',
      'Parents evening went well. Every parent asked about the explosions.',
    ],
  },
  {
    username: 'lucas_surf',
    displayName: 'Lucas Silva',
    bio: 'Surfer and ocean lover. Dawn patrol, salty hair, always checking the forecast.',
    posts: [
      'Dawn patrol. Glassy waves, nobody out. Perfect morning.',
      'The ocean always wins. Got tumbled for what felt like a minute.',
      'Beach cleanup this Saturday. Bring gloves, leave with a clear conscience.',
      'Waxed the board, checked the forecast three times. Flat. Classic.',
      'Surfing teaches patience. Most of it is sitting and waiting.',
    ],
  },
  {
    username: 'mia_frontend',
    displayName: 'Mia Johansson',
    bio: 'Frontend developer. Accessibility, CSS and design systems. Keyboard users matter.',
    posts: [
      'If you cannot use your app with only a keyboard, it is not finished.',
      'CSS grid solved in five lines what used to take me a whole afternoon.',
      'Accessibility audit found 40 issues. Fixed 38 today. Two to go.',
      'Buttons should be buttons. Not divs pretending to be buttons.',
      'Design system tip: name tokens by purpose, not by colour.',
      'Infinite scroll needs a way to reach the footer. Just saying.',
      'Wrote a component test that caught a real bug before it shipped. Tests are worth it.',
      'Dark mode shipped! Took three weeks, mostly arguing about shades of grey.',
    ],
  },
  {
    username: 'nathan_coffee',
    displayName: 'Nathan Price',
    bio: 'Barista and home roaster. Light roasts, pour-overs, and latte art fails.',
    posts: [
      'Nailed a tulip latte art today. First time in weeks. Someone frame this.',
      'Grind size matters more than your fancy equipment.',
      'Roasted a new Ethiopian coffee at home. Tastes like blueberries. Not kidding.',
      'Customer asked for "the strongest coffee you have". Gave them a ristretto and a warning.',
      'Coffee tip: use filtered water. Your coffee is 98% water after all.',
      'Tasting session with the team today. Six coffees before noon. Very focused. Very jittery.',
    ],
  },
  {
    username: 'fatima_writes',
    displayName: 'Fatima Zahra',
    bio: 'Novelist working on book two. Writing about family, cities and second chances.',
    posts: [
      'Wrote 2,000 words today. Deleted 1,500. That is how it goes.',
      'The second book is harder than the first. Nobody warned me.',
      "Best writing advice I ever got: finish the draft. You can't edit a blank page.",
      'Writing in a café because my apartment is too quiet. Writers are strange.',
      'Got a lovely email from a reader today. Framing it. Metaphorically.',
      'Chapter twelve finally makes sense. Only took three rewrites.',
      'Outlines are a map. You are allowed to take detours.',
    ],
  },
  {
    username: 'oscar_birds',
    displayName: 'Oscar Lindqvist',
    bio: 'Birdwatcher. Binoculars always in the bag. 212 species and counting.',
    posts: [
      'Spotted a kingfisher by the canal this morning. Species 212!',
      'Birdwatching is 90% standing still and 10% whispering "look, look".',
      'The robins in my garden have started building a nest. I am emotionally invested.',
      'Put up a feeder and the whole neighbourhood of sparrows moved in.',
      'Dawn chorus this morning was incredible. Worth waking up at 5.',
      'Learn a few bird songs. Every walk becomes a treasure hunt.',
    ],
  },
  {
    username: 'susan_knits',
    displayName: 'Susan Wright',
    bio: 'Knitter, crocheter, yarn hoarder. Currently making sweaters for the whole family.',
    posts: [
      'Finished a sweater after three months. It fits. I may cry.',
      'Yarn shop had a sale. I have no self-control and no regrets.',
      'Knitting on the train gets you the best conversations with strangers.',
      'Frogged half a scarf because I dropped a stitch 40 rows ago. Deep breaths.',
      'Teaching my niece to knit. She is already better at it than I was.',
      'Cosy socks season is here. Casting on three pairs at once, obviously.',
      'Knitting tip: always make a swatch. Always.',
    ],
  },
];
